name: The bitrise action

on: push

jobs:
  hello_world:
    name: Hello World 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        echo "Hello World"
