name: The bitrise action

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github_token: f19b59665cd94c71b54aa9a08b0c4f9c6ae2a7a7
          bitrise_app_slug: ca04e0425716e1ce
          bitrise_workflow: "primary"
          bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIA
